export const fishCollection = [
  {
    saltwater: true,
    harvestLocation: "Pacific Ocean",
    diet: "algae",
    name: "Malcolm",
    species: "Blue Tang",
    inches: 13,
    image: "bluetang.jpg",
  },
  {
    saltwater: true,
    harvestLocation: "Bali",
    diet: "really small fish",
    name: "Bob",
    species: "Guppy",
    inches: 3,
    image: "guppy.jpg",
  },
  {
    saltwater: true,
    harvestLocation: "Atlantic Ocean",
    diet: "squid",
    name: "BigBoss",
    species: "Amber Jack",
    inches: 60,
    image: "Amberjack.jpg",
  },
  {
    saltwater: true,
    harvestLocation: "Pacific Ocean",
    diet: "shellfish",
    name: "Jerry",
    species: "Swordfish",
    inches: 80,
    image: "swordfish.jpg",
  },
  {
    saltwater: true,
    harvestLocation: "Gulf of Mexico",
    diet: "tiny fish",
    name: "Predator",
    species: "Catfish",
    inches: 20,
    image: "catfish.jpg",
  },
  {
    saltwater: true,
    harvestLocation: "Atlantic Ocean",
    diet: "Herring",
    name: "Sabre",
    species: "Swordfish",
    inches: 117.6,
    image: "Swordfish2.jpg", 
  },
  {
    saltwater: false,
    harvestLocation: "Amazon Basin",
    diet: "brine shrimp",
    name: "Myrti",
    species: "Angel fish",
    inches: 12,
    image: "angelfish.webp",
  },
  {
    saltwater: true,
    harvestLocation: "Atlantic Ocean",
    diet: "Plankton",
    name: "Nemo",
    species: "Clownfish",
    inches: 4,
    image: "clownfish2.jpg",
  },
  {
    saltwater: false,
    harvestLocation: "Mississippi River",
    diet: "Everything",
    name: "Vacuum",
    species: "Catfish",
    inches: 24,
    image: "aquarium-catfish.jpg",
  },
  {
    saltwater: false,
    harvestLocation: "Bobbies Fish Emporium",
    diet: "minnows",
    name: "Ralph",
    species: "Smallmouth bass",
    inches: 14,
    image: "smallmouthBass.jpg",
  },
  {
    saltwater: "false",
    harvestLocation: "Cumberland River",
    diet: "anything",
    name: "Whiskers",
    species: "Ictalurus furcatus",
    inches: 39,
    image: "Ictalurusfurcatus.jpg",
  },
  {
    saltwater: true,
    harvestLocation: "South Pacific",
    diet: "shrimp",
    name: "Bruno",
    species: "Tuna",
    inches: 64,
    image: "tuna2.jpg",
  },
  {
    saltwater: false,
    harvestLocation: "Petsmart",
    diet: "algae",
    name: "Dorothy",
    species: "Goldfish",
    inches: 3,
    image: "gold-fish3.jpg",
  },
  {
    saltwater: false,
    harvestLocation: "Lake Tahoe",
    diet: "insects",
    name: "Trent",
    species: "Rainbow trout",
    inches: 21,
    image: "rainbowtrout.jpg",
  },
  {
    saltwater: true,
    harvestLocation: "Carribean Sea",
    diet: "shrimp",
    name: "Stephen",
    species: "Angler",
    inches: 23,
    image: "AnglerFish.jpg",
  },
  {
    saltwater: true,
    harvestLocation: "Barbados",
    diet: "anchoves",
    name: "Pizza",
    species: "Tuna",
    inches: 40,
    image: "tuna2.jpg",
  },
  {
    saltwater: false,
    harvestLocation: "TN River",
    diet: "Bacon",
    name: "Finn",
    species: "Bass",
    inches: 20,
    image: "bass.jpg",
  },
  {
    saltwater: true,
    harvestLocation: "Red Sea",
    diet: "mollusks",
    name: "Simba",
    species: "Lionfish",
    inches: 10,
    image: "lionfish.jpg",
  },
  {
    saltwater: true,
    harvestLocation: "New Zealand",
    diet: "Lost Sailors",
    name: "Tiki",
    species: "Parrot fish",
    inches: 36,
    image: "parrotfish.jpg",
  },
  {
    saltwater: true,
    harvestLocation: "Red Sea",
    diet: "algae",
    name: "Bobo",
    species: "Clown fish",
    inches: 5,
    image: "clownfish2.jpg",
  },
  {
    saltwater: true,
    harvestLocation: "Atlantic Sea",
    diet: "worms",
    name: "Flipper",
    species: "Garibaldi",
    inches: 12,
    image: "Garibaldi.jpg",

  },
  {
    saltwater: true,
    harvestLocation: "Bikini Bottom",
    diet: "Big Ole Fish",
    name: "Pearl",
    species: "Whale",
    inches: 1000,
    image: "whale.jpg",
  },
  {
    saltwater: false,
    harvestLocation: "Port Innsmouth",
    diet: "Primeval Shadows",
    name: "Cthulhu",
    species: "Clown fish",
    inches: 999,
    image: "clownfish3.jpg",
  },
  {
    saltwater: false,
    harvestLocation: "Amazon River",
    diet: "smaller fish",
    name: "Bitey",
    species: "Pirhana",
    inches: 7.5,
    image: "Pirhana2.jpg",
  },
  {
    saltwater: true,
    harvestLocation: "St.Croix",
    diet: "squid",
    name: "Crush",
    species: "Blue ting",
    inches: 7,
    image: "bluetang2.jpg",
  },

  {
    saltwater: false,
    harvestLocation: "Minnesota",
    diet: "Cherry Tomatoes",
    name: "Frank",
    species: "Piranha",
    inches: 7,
    image: "pirhana.jpg",
  },
  {
    saltwater: true,
    harvestLocation: "Atlantic, Pacific, and southern sea",
    diet: "smaller fish",
    name: "Bluefin tuna",
    species: "Thunnus thynnus",
    inches: 84,
    image: "thunnus-thynnus.jpg",
  },
  {
    saltwater: true,
    harvestLocation: "Baltic Sea",
    diet: "smaller fish",
    name: "Fil",
    species: "Goldfish",
    inches: 40,
    image: "goldfish.jpg",
  },
];


export const getFish = () => {
	//do some math
	//sort out the fish
	//and then return
	return fishCollection;
}